# Generated by Django 5.1.7 on 2025-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
