# Generated by Django 5.2.1 on 2025-05-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_postcategory_threadcategory_thread_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Thread Categories'},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='image',
        ),
        migrations.AddField(
            model_name='thread',
            name='optional_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Optional Image'),
        ),
    ]
