# Generated by Django 5.2.1 on 2025-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_comment_author_alter_thread_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='optional_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Optional Image'),
        ),
    ]
