# Generated by Django 5.1.6 on 2025-05-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0005_alter_product_owner_alter_transaction_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Out of Stock', 'NO_STOCK'), ('On Sale', 'SALE'), ('Available', 'STOCK')], default='AVAILABLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('On cart', 'CART'), ('To Pay', 'PAY'), ('To Ship', 'SHIPPING'), ('To Recieve', 'TRANSIT'), ('Delivered', 'DONE')], default='CART', max_length=255),
        ),
    ]
