# Generated by Django 5.1.6 on 2025-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_remove_commission_people_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='people_required',
            field=models.IntegerField(default=0),
        ),
    ]
