# Generated by Django 5.1.6 on 2025-05-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commission_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='author',
        ),
    ]
