# Generated by Django 5.1.6 on 2025-05-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commission_people_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', 'applied_on'], 'verbose_name': 'job application', 'verbose_name_plural': 'job applications'},
        ),
    ]
