# Generated by Django 5.1.6 on 2025-05-11 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commission_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['status', 'created_on'], 'verbose_name': 'commission', 'verbose_name_plural': 'commissions'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('1_open', 'Open'), ('2_full', 'Full'), ('3_completed', 'Completed'), ('4_discontinued', 'Discontinued')], max_length=14),
        ),
        migrations.AlterField(
            model_name='job',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='commissions.commission'),
        ),
    ]
