# Generated by Django 5.1.6 on 2025-05-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_commission_options_alter_commission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('A_open', 'Open'), ('B_full', 'Full'), ('C_completed', 'Completed'), ('D_discontinued', 'Discontinued')], max_length=14),
        ),
    ]
