# Generated by Django 5.1.6 on 2025-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_commission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-status', 'created_on'], 'verbose_name': 'commission', 'verbose_name_plural': 'commissions'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('A_OPEN', 'AOpen'), ('B_FULL', 'Full'), ('C_COMPLETED', 'Completed'), ('D_DISCONTINUED', 'Discontinued')], max_length=14),
        ),
    ]
