# Generated by Django 5.1.6 on 2025-05-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-status', '-manpower_required', 'role'], 'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Full', 'Full'), ('Completed', 'Completed'), ('Discontinued', 'Discontinued')], default='Open', max_length=14),
        ),
    ]
